### ISSUE TITLE
Documents upload not working

### ISSUE THREAD

**Issue by IceAgeEcologist** [NeotomaDB/Website#4]
Am trying to upload new documents to Neotoma website (my ESA powerpoint) and running into access issues.  I suspect access/permissions have been changed on the PSU side.  

URL: https://www.neotomadb.org/documents

Clicking 'add' leads to a server connection error.

I'm logged in to the Neotoma website.

**Comment by stryker-m** [comment]
@IceAgeEcologist This should be fixed.  The form template referenced the old http URL.

**Comment by IceAgeEcologist** [comment]
Thanks, Mike. Fix has improved things - 'add' button now works and I can create a new news item. However, trying to attach and upload a file creates an error message: Document Item: The file could not be written to disk.

**Comment by stryker-m** [comment]
I tested uploading a file ~20MB which worked.  There is a 32MB limit on uploads but you should receive an error explaining the filesize limit has been exceeded.  For now, if you post the file to our Google docs directory, I can upload it to the webserver for access from the documents entry you created.

**Comment by IceAgeEcologist** [comment]
OK, thanks.  I've just posted the powerpoint to be uploaded to [Drive](https://drive.google.com/open?id=1ygZVSQMIaIItJORTVv-41XS6LkQPh5eu)

The file size is ~6MB, so file size limits don't seem to be the problem.  I'm worried that PSU is requiring VPN or something else that is precluding third-party uploads by registered Neotoma folks to the server.

**Comment by jessicablois** [comment]
I just tried uploading my GeoDaRRS talk and received the same error. My file is 5.9 MB so it should work.

The form you submitted contained the following errors

  *   Document Item - The file could not be written to disk.

Best,
Jessica

------------------------------------------
Associate Professor
School of Natural Sciences
University of California, Merced

Office: SE1 296
Phone: (209) 228-2256
Email: jblois@ucmerced.edu<mailto:jblois@ucmerced.edu>
Web: http://jessicablois.com

On Aug 10, 2018, at 5:43 AM, Jack Williams <notifications@github.com<mailto:notifications@github.com>> wrote:


OK, thanks. I've just posted the powerpoint to be uploaded to Drive<https://drive.google.com/open?id=1ygZVSQMIaIItJORTVv-41XS6LkQPh5eu>

The file size is ~6MB, so file size limits don't seem to be the problem. I'm worried that PSU is requiring VPN or something else that is precluding third-party uploads by registered Neotoma folks to the server.

**Comment by stryker-m** [comment]
@IceAgeEcologist the ESA pptx is now uploaded. 
@jessicablois you should now be able to create a new entry with an uploaded document.  Something about uploads was triggering the cross-site scripting security filter.  You should both be able to upload documents using your accounts.

**Comment by stryker-m** [comment]
Glad to hear it.  You're welcome.
